# Meta Data for SEO

## Homepage
title = "NipoPlus"
titleSeparator = "|"
titleAddition = "ãƒãƒ¼ã‚³ãƒ¼ãƒ‰ã§å ±å‘Šæ›¸ã‚’ã‚¢ãƒ—ãƒªåŒ–"
description = "ãƒã‚§ãƒƒã‚¯ã‚·ãƒ¼ãƒˆã‚„æ—¥å ±ã‚‚OKã€‚ã‚¹ãƒãƒ›ã§æ—¥å ±ä½œæˆã‚„æ‰¿èªæ£„å´ã€å ±å‘Šæ›¸ã®é›†è¨ˆ&ã‚°ãƒ©ãƒ•åŒ–ğŸ“Šã ã£ã¦å¯èƒ½ã§ã™ã€‚ç„¡æ–™ãƒ—ãƒ©ãƒ³æœ‰ã‚Šã€¼æœ‰æ–™ãƒ—ãƒ©ãƒ³ã‚‚æ¥­ç•Œæœ€å®‰å€¤"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["/images/nipoplus.png"]
ogLocale = "ja_JP"
domainTLD = "nipo-plus-doc.sndbox.jp"
titleHome = "å ±å‘Šæ›¸App NipoPlus"

## Twitter Cards
twitterSite = "@nipo_plus"
twitterCreator = "@nipo_plus"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "NipoPlus"
schemaAuthor = "Nipo Plus"
schemaAuthorTwitter = "https://twitter.com/nipo_plus"
schemaAuthorGitHub = "https://github.com/sandbox-co-ltd"
schemaLocale = "ja-JP"
schemaLogo = "/images/nipoplus.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "/images/banner.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/nipo_plus"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/sandbox-co-ltd"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "é–‹ç™ºé‹å–¶:<a class=\"text-muted\" href=\"https://sndbox.jp/\">åˆåŒä¼šç¤¾ã‚µãƒ³ãƒ‰ãƒœãƒƒã‚¯ã‚¹</a> / å”åŠ›: <a class=\"text-muted\" href=\"https://pandafirm.jp/\">ãƒ‘ãƒ³ãƒ€å•†ä¼š</a> "

# Feed
copyRight = "Copyright (c) Sndbox LLC"

# Alert
alert = false
alertDismissable = true
alertText = "2023/05/28 ã‚µã‚¤ãƒˆãƒªãƒ‹ãƒ¥ãƒ¼ã‚¢ãƒ«ã—ã¾ã—ãŸ"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/sandbox-co-ltd/hugo_nipo_plus"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = true

[sections]
  sectionNav = ["docs"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = false
  bootStrapJs = true
  breadCrumb = true
  highLight = false
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = true
  navbarSticky = true
  toTopButton = false
  scrollSpy = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
