baseURL = 'https://nipo-plus-doc.sndbox.jp/'
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = 'NipoPlus'
theme = "learn"
canonifyurls = true
enableGitInfo = true

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
  
[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = "https://github.com/sandbox-co-ltd/hugo_nipo_plus/edit/main/content/"
  # Author of the site, will be used in meta information
  author = "sandbox co.,ltd"
  # Description of the site, will be used in meta information
  description = "日報・チェックシート管理アプリ。スマホ・タブレット・PC対応のクラウド型です。自由にテンプレート設計可能。集計やPDF出力機能も。2ヶ月の無料お試しあり。業界最安値1名180円。製造業、営業、研修など様々な用途にご利用可能です"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = true
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # If set to false, a Home button will appear below the search bar on the menu.
  # It is redirecting to the landing page of the current language if specified. (Default is "/")
  disableLandingPageButton = true
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  # パンくずリストは改造して常に表示されるようにしたため以下のパラメータは指定しても無意味である
  # disableBreadcrumb = true
  # If set to true, prevents Hugo from including the mermaid module if not needed (will reduce load times and traffic)
  disableMermaid = false
  # Specifies the remote location of the mermaid js
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  # customMermaidURL = "https://nipo-plus-doc.sndbox.jp/mermaid.min.js"
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = ""
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  # custom_css = ["css/css.css"]
  # Change the title separator. Default to "::".
  titleSeparator = "|"


[[menu.shortcuts]]
name = "<i class='fa fa-search'></i> 検索"
url = "/search/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-cube'></i>リリースノート"
url = "/system/release-note/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-cube'></i>旧Nipoとの違い"
url = "/system/about/"
weight = 21

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> お問い合わせ"
url = "/system/inquery"
weight = 30

[outputs]
   home = [ "HTML", "JSON" ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true