
[[main]]
  name = "ğŸ“–æ“ä½œã‚¬ã‚¤ãƒ‰"
  url = "/docs/manual/quickstart/"
  weight = 10
[[main]]
  name = "é€†å¼•ãè¾å…¸"
  identifier = "reverse-lookup/about/about"
  url = "/reverse-lookup/"
  weight = 15

[[main]]
  name = "ğŸ’°æ–™é‡‘"
  url = "/docs/price/_about/"
  weight = 20
[[main]]
  name = "ğŸ“©å•åˆã›ãƒ»æ¤œç´¢"
  url = "/others/inquery/"
  weight = 30
[[main]]
  name = "ğŸ’¡æ´»ç”¨ä¾‹"
  url = "/tips/"
  weight = 45
[[main]]
  name = "Excelæ´»ç”¨"
  weight = 48
  identifier = "excel"
  url = "/excel/"

[[main]]
  name = "ãã®ä»–"
  weight = 50
  identifier = "blogroot"
  url = ""
[[main]]
  name = "ãƒ‹ãƒ¥ãƒ¼ã‚¹"
  weight = 51
  identifier = "news"
  url = "/news/"
  parent = "blogroot"
[[main]]
  name = "æŠ€è¡“ç³»ãƒ–ãƒ­ã‚°"
  weight = 52
  identifier = "tech"
  url = "/tech/"
  parent = "blogroot"

[[footer]]
  name = "Tags"
  url = "/tags/"
  weight = 20


[[sidebar_tips]]
  name = "æ´»ç”¨è¡“Tips"
  pageRef = "/tips"
  weight = 10


[[sidebar_excel]]
  name = "ã‚¨ã‚¯ã‚»ãƒ«æ´»ç”¨è¡“"
  pageRef = "/excel"
  weight = 13


[[sidebar_others]]
  name = "å•ã„åˆã‚ã›ç­‰"
  pageRef = "/others"
  weight = 13


[[sidebar_1_test]]
  name = "ã‚ã„ã†ãˆãŠ"
  pageRef = "/1_test"
  weight = 10


[[sidebar_test]]
  name = "ã‹ããã‘ã“"
  pageRef = "/docs"
  weight = 13
