
[[main]]
  name = "ğŸ“–æ“ä½œã‚¬ã‚¤ãƒ‰"
  url = "/docs/manual/quickstart/"
  weight = 10
[[main]]
  name = "ãƒ¦ãƒ¼ã‚¹ã‚±ãƒ¼ã‚¹"
  url = "/tips/"
  weight = 11

[[main]]
  name = "ğŸ’°æ–™é‡‘"
  url = "/docs/price/_about/"
  weight = 20

[[main]]
  name = "ğŸ“©ãŠå•ã„åˆã‚ã›"
  url = "/others/inquery/"
  weight = 40


[[main]]
  name = "æ—§Nipo"
  url = "/docs/old/quick/"
  weight = 40

[[main]]
  name = "ãƒ–ãƒ­ã‚°"
  weight = 50
  identifier = "blogroot"
  url = ""

[[main]]
  name = "ãƒ‹ãƒ¥ãƒ¼ã‚¹"
  weight = 51
  identifier = "news"
  url = "/news/"
  parent = "blogroot"

[[main]]
  name = "æŠ€è¡“ç³»ãƒ–ãƒ­ã‚°"
  weight = 52
  identifier = "tech"
  url = "/tech/"
  parent = "blogroot"


[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/nipo_plus"
  weight = 20

