
[[main]]
  name = "ğŸ“–æ“ä½œã‚¬ã‚¤ãƒ‰"
  url = "/docs/manual/quickstart/"
  weight = 10
[[main]]
  name = "é€†å¼•ãè¾å…¸"
  identifier = "reverse-lookup/about/about"
  url = "/reverse-lookup/about/about/"
  weight = 15

[[main]]
  name = "ğŸ’°æ–™é‡‘"
  url = "/docs/price/_about/"
  weight = 20
[[main]]
  name = "ğŸ“©å•åˆã›"
  url = "/others/inquery/"
  weight = 30
[[main]]
  name = "ğŸ”æ¤œç´¢"
  url = "/others/search/"
  weight = 40
[[main]]
  name = "ğŸ’¡æ´»ç”¨ä¾‹"
  url = "/tips/about/about/"
  weight = 45
[[main]]
  name = "ãã®ä»–"
  weight = 50
  identifier = "blogroot"
  url = ""
[[main]]
  name = "ãƒ‹ãƒ¥ãƒ¼ã‚¹"
  weight = 51
  identifier = "news"
  url = "/news/"
  parent = "blogroot"
[[main]]
  name = "æŠ€è¡“ç³»ãƒ–ãƒ­ã‚°"
  weight = 52
  identifier = "tech"
  url = "/tech/about/about/"
  parent = "blogroot"
[[main]]
  name = "Excelæ´»ç”¨è¡“"
  weight = 48
  identifier = "excel"
  url = "/excel/about/about/"
  parent = "blogroot"

[[footer]]
  name = "Tags"
  url = "/tags/"
  weight = 20


# [[sidebar_docs]]
#   name = "Guides"
#   pageRef = "/docs"
#   weight = 10
