
[[main]]
  name = "ğŸ“–æ“ä½œã‚¬ã‚¤ãƒ‰"
  url = "/docs/manual/quickstart/"
  weight = 10


[[main]]
  name = "ğŸ’°æ–™é‡‘"
  url = "/docs/price/_about/"
  weight = 20

[[main]]
  name = "ğŸ“©å•åˆã›"
  url = "/others/inquery/"
  weight = 40



[[main]]
  name = "æ´»ç”¨ä¾‹"
  url = "/tips/"
  weight = 45


[[main]]
  name = "ãƒ–ãƒ­ã‚°"
  weight = 50
  identifier = "blogroot"
  url = ""

[[main]]
  name = "ãƒ‹ãƒ¥ãƒ¼ã‚¹"
  weight = 51
  identifier = "news"
  url = "/news/"
  parent = "blogroot"

[[main]]
  name = "æŠ€è¡“ç³»ãƒ–ãƒ­ã‚°"
  weight = 52
  identifier = "tech"
  url = "/tech/"
  parent = "blogroot"
[[main]]
  name = "Excelæ´»ç”¨è¡“"
  weight = 48
  identifier = "excel"
  url = "/excel/"
  parent = "blogroot"
