
[[main]]
  name = "ğŸ“–æ“ä½œã‚¬ã‚¤ãƒ‰"
  url = "/docs/manual/quickstart/"
  weight = 10


[[main]]
  name = "ğŸ’°æ–™é‡‘"
  url = "/docs/price/_about/"
  weight = 20

[[main]]
  name = "ğŸ“©ãŠå•ã„åˆã‚ã›"
  url = "/others/inquery/"
  weight = 40


[[main]]
  name = "æ—§Nipo"
  url = "/legacy/about/diff/"
  weight = 40

[[main]]
  name = "ãƒ¦ãƒ¼ã‚¹ã‚±ãƒ¼ã‚¹"
  url = "/tips/"
  weight = 45


[[main]]
  name = "ãƒ–ãƒ­ã‚°"
  weight = 50
  identifier = "blogroot"
  url = ""

[[main]]
  name = "ãƒ‹ãƒ¥ãƒ¼ã‚¹"
  weight = 51
  identifier = "news"
  url = "/news/"
  parent = "blogroot"

[[main]]
  name = "æŠ€è¡“ç³»ãƒ–ãƒ­ã‚°"
  weight = 52
  identifier = "tech"
  url = "/tech/"
  parent = "blogroot"
